#!/bin/bash


# Add optimathsat to the path
mkdir -p ~/.local/bin
# to create alias for optimathsat ("~/.local/bin" is in the PATH)
cd ~/.local/bin
#ln -s ~/optimathsat/optimathsat optimathsat
# Dockerfile also has copying the directory to /usr/bin; I don't know if that is necessary or not
cd ~
#cp -r optimathsat /usr/bin
cp -r optimathsat ~/.local/bin
chmod 777 ~/.local/bin/optimathsat
chmod 777 ~/.local/bin/optimathsat/optimathsat

# Move minizinc installation to here because I cannot see how to use it when using apt-get installed one
# based on https://www.minizinc.org/doc-2.5.5/en/installation_detailed_linux.html#minizinc and  https://stackoverflow.com/q/68126984/8508004
wget https://github.com/MiniZinc/libminizinc/archive/refs/tags/2.6.4.zip
unzip 2.6.4.zip 
cd libminizinc-2.6.4/
mkdir build
cd build/
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
cd ~/.local/bin
ln -s ~/libminizinc-2.6.4/build/minizinc minizinc